version: "3"
services:
  db:
    image: "postgres:12"
    container_name: "sirka_db"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: test_case

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "sirka_api"
    depends_on:
      - db
    ports:
      - '8001:8080'
    environment:
      DB_HOST: db
      DB_USER: dev
      DB_PASSWORD: dev
      DB_PORT: 5432
      DB_NAME: test_case
      DB_SSL_MODE: disable
